---
name: "M3U Exporter"
guid: "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Export Music Playlists as M3U files"
description: >
  Export user music playlists to M3U files with configurable export directory
  and user selection. Creates a scheduled task to automate exports.
category: "General"
owner: "jakepi84"
artifacts:
- "Jellyfin.Plugin.M3UExporter.dll"
changelog: >
  Initial release - Export music playlists to M3U format
